### ISSUE TITLE
Thanks very much for your citation of my library @duan2023pypop7, I will integrate your library into my library if possible.

### ISSUE THREAD

**Issue by Evolutionary-Intelligence** [PdIPS/CBX#2]
First thanks very much for your citation of my black-box optimization library @duan2023pypop7 in your documentation.

**I will integrate your interesting library into my library and documentation, if possible.**

Thanks very much again.

**Comment by TimRoith** [comment]
Thanks a lot for your interest and the possible integration! I am really looking forward to it. Please feel free to open issues here, or on the Python repo, if any question arise.

Best
Tim
